### ISSUE TITLE
could not set up wifi access point with RZ 608 on ubuntu 22.04

### ISSUE THREAD

**Issue by zeddit** [ShadowBlip/rz608-fix#3]
hi all, I am using RZ608 wifi card on ubuntu 22.04 to set up an wifi access point.
I am using netplan and NetworkManager to set the wifi in ap mode.
However, devices could not connect to the ap and sudo wpa_cli -i wlp2s0 status shows

bssid=10:6f:d9:af:56:c5
freq=2412
ssid=test
id=0
mode=AP
pairwise_cipher=CCMP
group_cipher=CCMP
key_mgmt=UNKNOWN <- this problem. 
wpa_state=COMPLETED
ip_address=192.168.18.1
key_mgmt should be WPA2-PSK or something else. so is the issue related to the driver mt7921e.
how could I fix it, great thanks.

I alse mentioned problem here. https://github.com/morrownr/USB-WiFi/issues/66

 how could I debug this and find the solution. could you please give me some advices. great thanks.

**Comment by pastaq** [comment]
What kernel are you using?

**Comment by zeddit** [comment]
@pastaq thanks for your reply.
I am using 5.15.0-87-generic.
After changing to hostapd, the problem solved.
